version: '2.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.123.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  restproxy:
    image: confluentinc/cp-kafka-rest:5.3.3
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8082:8082
      - 39999:39999
    environment:
      KAFKA_REST_HOST_NAME: 172.16.123.1
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_ZOOKEEPER_CONNECT: 172.16.123.1:2181
      KAFKA_REST_JMX_PORT: 39999 
      KAFKA_REST_LOG4J_ROOT_LOGLEVEL: DEBUG 
